// A4 print of the day dossier — the artifact that actually leaves the app when
// a punch is contested (attached to a letter, handed to a consulente del
// lavoro, filed with an inspection). It states three things per punch: what the
// employee stamped, what the value is now, and every step in between with the
// name of whoever took it.
import PDFDocument from 'pdfkit';
import type { DayDossier, DossierStamp } from './stamp-dossier.js';
import type { StampChangeKind, StampHistoryEvent, TrackedField } from './stamp-history.js';

const MARGIN = 40;
const FOOTER_H = 24;

const LABELS = {
  it: {
    title: 'Prospetto timbrature — dossier giornata',
    employee: 'Dipendente',
    externalId: 'Identificativo',
    day: 'Giorno',
    generatedAt: 'Generato il',
    generatedBy: 'Generato da',
    stamps: 'Timbrature della giornata',
    noStamps: 'Nessuna timbratura registrata in questa giornata.',
    originalValue: 'Timbrato dal dipendente',
    currentValue: 'Valore attuale',
    unchanged: 'Non modificata',
    deleted: 'ELIMINATA',
    deletedBy: 'Eliminata da',
    reason: 'Motivo',
    origin: 'Origine',
    branch: 'Sede',
    device: 'Dispositivo',
    notes: 'Note',
    trail: 'Storico modifiche',
    justifications: 'Anomalie giustificate',
    corrections: 'Richieste di correzione',
    status: 'Stato',
    requested: 'Richiesta',
    resolvedBy: 'Decisa da',
    page: 'Pagina',
    of: 'di',
    disclaimer:
      'Documento generato automaticamente dal registro delle timbrature. Lo storico delle modifiche è in sola aggiunta: nessuna riga può essere alterata o rimossa a posteriori.',
    outOfArea: 'fuori area',
    mock: 'posizione sospetta',
  },
  en: {
    title: 'Attendance statement — day dossier',
    employee: 'Employee',
    externalId: 'Unique id',
    day: 'Day',
    generatedAt: 'Generated on',
    generatedBy: 'Generated by',
    stamps: 'Stamps of the day',
    noStamps: 'No stamp recorded on this day.',
    originalValue: 'Stamped by the employee',
    currentValue: 'Current value',
    unchanged: 'Not modified',
    deleted: 'DELETED',
    deletedBy: 'Deleted by',
    reason: 'Reason',
    origin: 'Origin',
    branch: 'Site',
    device: 'Device',
    notes: 'Notes',
    trail: 'Change history',
    justifications: 'Justified anomalies',
    corrections: 'Correction requests',
    status: 'Status',
    requested: 'Requested',
    resolvedBy: 'Decided by',
    page: 'Page',
    of: 'of',
    disclaimer:
      'Document generated automatically from the stamp register. The change history is append-only: no row can be altered or removed after the fact.',
    outOfArea: 'out of area',
    mock: 'suspicious location',
  },
} as const;

type Lang = 'it' | 'en';
type Labels = (typeof LABELS)[Lang];

const EVENT_LABEL: Record<Lang, Record<string, string>> = {
  it: {
    clock_in: 'Entrata',
    clock_out: 'Uscita',
    break_start: 'Inizio pausa',
    break_end: 'Fine pausa',
    lunch_start: 'Inizio pausa pranzo',
    lunch_end: 'Fine pausa pranzo',
  },
  en: {
    clock_in: 'Clock in',
    clock_out: 'Clock out',
    break_start: 'Break start',
    break_end: 'Break end',
    lunch_start: 'Lunch start',
    lunch_end: 'Lunch end',
  },
};

const SOURCE_LABEL: Record<Lang, Record<string, string>> = {
  it: {
    employee_app: 'App dipendente',
    employee_correction: 'Correzione dipendente',
    admin_manual: 'Inserimento admin',
    system_auto: 'Automatica',
  },
  en: {
    employee_app: 'Employee app',
    employee_correction: 'Employee correction',
    admin_manual: 'Admin entry',
    system_auto: 'Automatic',
  },
};

const KIND_LABEL: Record<Lang, Record<StampChangeKind, string>> = {
  it: {
    employee_stamp: 'Timbratura del dipendente',
    employee_undo: 'Annullata dal dipendente (entro 60s)',
    employee_correction: 'Richiesta di correzione approvata',
    admin_create: 'Inserita da un amministratore',
    admin_edit: 'Modificata da un amministratore',
    admin_delete: 'Eliminata da un amministratore',
    anomaly_fix: 'Correzione anomalia (orario standard)',
    bulk_apply: 'Applicazione massiva orario standard',
    auto_clockout: 'Uscita automatica dopo 15 ore',
    unknown: 'Modifica',
  },
  en: {
    employee_stamp: 'Employee stamp',
    employee_undo: 'Undone by the employee (within 60s)',
    employee_correction: 'Correction request approved',
    admin_create: 'Added by an administrator',
    admin_edit: 'Modified by an administrator',
    admin_delete: 'Deleted by an administrator',
    anomaly_fix: 'Anomaly fix (standard schedule)',
    bulk_apply: 'Bulk standard-schedule apply',
    auto_clockout: 'Automatic clock-out after 15 hours',
    unknown: 'Change',
  },
};

const FIELD_LABEL: Record<Lang, Record<TrackedField, string>> = {
  it: {
    event_type: 'Evento',
    occurred_at: 'Data e ora',
    branch_id: 'Sede',
    notes: 'Note',
    source: 'Origine',
    deleted_at: 'Eliminazione',
  },
  en: {
    event_type: 'Event',
    occurred_at: 'Date and time',
    branch_id: 'Site',
    notes: 'Notes',
    source: 'Origin',
    deleted_at: 'Deletion',
  },
};

// Same twelve kinds as the zod enum in routes/shifts.ts and the web
// common:anomaly.* labels — keep the three in sync.
const ANOMALY_LABEL: Record<Lang, Record<string, string>> = {
  it: {
    missing_clock_in: 'Entrata mancante',
    missing_clock_out: 'Uscita mancante',
    late_clock_in: 'Entrata in ritardo',
    early_clock_out: 'Uscita anticipata',
    short_hours: 'Ore giornaliere insufficienti',
    worked_on_rest_day: 'Lavoro in giorno di riposo',
    break_too_short: 'Pausa troppo breve',
    break_too_long: 'Pausa troppo lunga',
    lunch_too_short: 'Pausa pranzo troppo breve',
    lunch_too_long: 'Pausa pranzo troppo lunga',
    lunch_outside_window: 'Pausa pranzo fuori finestra',
    clock_out_out_of_area: 'Uscita fuori area',
  },
  en: {
    missing_clock_in: 'Missing clock-in',
    missing_clock_out: 'Missing clock-out',
    late_clock_in: 'Late clock-in',
    early_clock_out: 'Early clock-out',
    short_hours: 'Insufficient daily hours',
    worked_on_rest_day: 'Worked on a rest day',
    break_too_short: 'Break too short',
    break_too_long: 'Break too long',
    lunch_too_short: 'Lunch break too short',
    lunch_too_long: 'Lunch break too long',
    lunch_outside_window: 'Lunch break outside window',
    clock_out_out_of_area: 'Clock-out outside area',
  },
};

const CORRECTION_STATUS: Record<Lang, Record<string, string>> = {
  it: { pending: 'In attesa', approved: 'Approvata', rejected: 'Respinta' },
  en: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected' },
};

const locale = (lang: Lang): string => (lang === 'it' ? 'it-IT' : 'en-GB');

function fmtDateTime(value: string | null, lang: Lang, timeZone: string): string {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  return d.toLocaleString(locale(lang), {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone,
  });
}

function fmtTime(value: string | null, lang: Lang, timeZone: string): string {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  return d.toLocaleTimeString(locale(lang), { hour: '2-digit', minute: '2-digit', timeZone });
}

function fmtDay(dateIso: string, lang: Lang): string {
  const d = new Date(`${dateIso}T00:00:00`);
  if (Number.isNaN(d.getTime())) return dateIso;
  return d.toLocaleDateString(locale(lang), {
    weekday: 'long',
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
}

/**
 * A tracked field's raw jsonb text, rendered the way the reader expects.
 * branch_id stays a uuid on purpose — the dossier resolves the *current* branch
 * name in the header, and inventing a name for a historical id would be a claim
 * the audit trail does not actually support.
 */
function fmtFieldValue(
  field: TrackedField,
  raw: string | null,
  lang: Lang,
  timeZone: string,
  labels: Labels
): string {
  if (raw === null) return '—';
  switch (field) {
    case 'occurred_at':
      return fmtDateTime(raw, lang, timeZone);
    case 'deleted_at':
      return `${labels.deleted} · ${fmtDateTime(raw, lang, timeZone)}`;
    case 'event_type':
      return EVENT_LABEL[lang][raw] ?? raw;
    case 'source':
      return SOURCE_LABEL[lang][raw] ?? raw;
    default:
      return raw;
  }
}

export interface DossierPdfInput {
  dossier: DayDossier;
  language?: Lang;
  /** Tenant zone the times are printed in (Europe/Rome unless overridden). */
  timeZone?: string;
}

export function buildDayDossierPdf(input: DossierPdfInput): Promise<Buffer> {
  const lang: Lang = input.language ?? 'it';
  const labels = LABELS[lang];
  const timeZone = input.timeZone ?? 'Europe/Rome';
  const d = input.dossier;

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: MARGIN, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const contentW = doc.page.width - MARGIN * 2;
    const bottomLimit = (): number => doc.page.height - MARGIN - FOOTER_H;
    const ensureSpace = (needed: number): void => {
      if (doc.y + needed > bottomLimit()) doc.addPage();
    };
    const rule = (): void => {
      doc
        .moveTo(MARGIN, doc.y)
        .lineTo(MARGIN + contentW, doc.y)
        .strokeColor('#cbd5e1')
        .lineWidth(0.5)
        .stroke();
    };
    const sectionTitle = (text: string): void => {
      ensureSpace(46);
      doc.moveDown(0.6);
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#15569e').text(text, { width: contentW });
      doc.moveDown(0.2);
      rule();
      doc.moveDown(0.35);
    };

    /* ----- Header ----- */
    doc.font('Helvetica-Bold').fontSize(16).fillColor('#0f172a').text(d.tenant_name);
    doc.moveDown(0.2);
    doc.fontSize(12).fillColor('#15569e').text(labels.title);
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(9).fillColor('#475569');
    doc.text(`${labels.employee}: ${d.user.name}${d.user.email ? ` (${d.user.email})` : ''}`);
    if (d.user.external_id) doc.text(`${labels.externalId}: ${d.user.external_id}`);
    doc.text(`${labels.day}: ${fmtDay(d.date, lang)}`);
    doc.text(`${labels.generatedAt}: ${fmtDateTime(d.generated_at, lang, timeZone)}`);
    if (d.generated_by) doc.text(`${labels.generatedBy}: ${d.generated_by}`);
    doc.moveDown(0.4);
    rule();

    /* ----- Stamps ----- */
    sectionTitle(labels.stamps);
    if (d.stamps.length === 0) {
      doc.font('Helvetica').fontSize(10).fillColor('#475569').text(labels.noStamps);
    }
    for (const s of d.stamps) {
      renderStamp(s);
    }

    /* ----- Justified anomalies ----- */
    if (d.justifications.length > 0) {
      sectionTitle(labels.justifications);
      for (const j of d.justifications) {
        ensureSpace(34);
        const kindLabel = ANOMALY_LABEL[lang][j.anomaly_kind] ?? j.anomaly_kind;
        doc.font('Helvetica-Bold').fontSize(9).fillColor('#334155').text(kindLabel);
        doc
          .font('Helvetica')
          .fontSize(9)
          .fillColor('#475569')
          .text(
            `${j.note}  —  ${j.created_by_name ?? '—'}, ${fmtDateTime(j.created_at, lang, timeZone)}`,
            { width: contentW }
          );
        doc.moveDown(0.3);
      }
    }

    /* ----- Correction requests ----- */
    if (d.corrections.length > 0) {
      sectionTitle(labels.corrections);
      for (const c of d.corrections) {
        ensureSpace(40);
        const ev = EVENT_LABEL[lang][c.claimed_event_type] ?? c.claimed_event_type;
        doc
          .font('Helvetica-Bold')
          .fontSize(9)
          .fillColor('#334155')
          .text(`${ev} — ${fmtDateTime(c.claimed_occurred_at, lang, timeZone)}`);
        doc.font('Helvetica').fontSize(9).fillColor('#475569');
        doc.text(`${labels.reason}: ${c.justification}`, { width: contentW });
        const status = CORRECTION_STATUS[lang][c.status] ?? c.status;
        const decided = c.resolved_at
          ? ` — ${labels.resolvedBy}: ${c.resolved_by_name ?? '—'}, ${fmtDateTime(c.resolved_at, lang, timeZone)}`
          : '';
        doc.text(`${labels.status}: ${status}${decided}`, { width: contentW });
        if (c.resolution_note) doc.text(c.resolution_note, { width: contentW });
        doc.moveDown(0.3);
      }
    }

    /* ----- Disclaimer ----- */
    ensureSpace(50);
    doc.moveDown(0.6);
    rule();
    doc.moveDown(0.3);
    doc.font('Helvetica-Oblique').fontSize(7.5).fillColor('#94a3b8').text(labels.disclaimer, {
      width: contentW,
    });

    /* ----- Page numbers ----- */
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      doc
        .font('Helvetica')
        .fontSize(8)
        .fillColor('#94a3b8')
        .text(
          `${d.user.name} — ${d.date}    ${labels.page} ${i + 1} ${labels.of} ${range.count}`,
          MARGIN,
          doc.page.height - MARGIN - 10,
          { width: contentW, align: 'right', lineBreak: false }
        );
    }

    /* ----- one punch: heading, original-vs-current, then its trail ----- */
    function renderStamp(s: DossierStamp): void {
      ensureSpace(70);
      const eventNow = EVENT_LABEL[lang][s.event_type] ?? s.event_type;
      const deleted = s.deleted_at !== null;

      doc
        .font('Helvetica-Bold')
        .fontSize(10)
        .fillColor(deleted ? '#b91c1c' : '#0f172a')
        .text(
          `${fmtTime(s.occurred_at, lang, timeZone)}  ${eventNow}${deleted ? `   [${labels.deleted}]` : ''}`,
          { width: contentW }
        );

      doc.font('Helvetica').fontSize(9).fillColor('#334155');

      // The two lines a contestation actually turns on. Printed even when the
      // punch is untouched, so the absence of a change is stated rather than
      // merely implied by an empty section.
      if (s.original_occurred_at || s.original_event_type) {
        const origEvent = s.original_event_type
          ? (EVENT_LABEL[lang][s.original_event_type] ?? s.original_event_type)
          : eventNow;
        const origWhen = s.original_occurred_at
          ? fmtDateTime(s.original_occurred_at, lang, timeZone)
          : fmtDateTime(s.occurred_at, lang, timeZone);
        doc.fillColor('#b45309').text(`${labels.originalValue}: ${origWhen} — ${origEvent}`, {
          width: contentW,
        });
        doc
          .fillColor('#334155')
          .text(
            `${labels.currentValue}: ${fmtDateTime(s.occurred_at, lang, timeZone)} — ${eventNow}` +
              (s.edited_by_name ? `  (${s.edited_by_name}, ${fmtDateTime(s.edited_at, lang, timeZone)})` : ''),
            { width: contentW }
          );
      } else {
        doc.fillColor('#475569').text(labels.unchanged, { width: contentW });
      }

      const meta: string[] = [`${labels.origin}: ${SOURCE_LABEL[lang][s.source] ?? s.source}`];
      if (s.branch_name) meta.push(`${labels.branch}: ${s.branch_name}`);
      if (s.device_platform) {
        meta.push(
          `${labels.device}: ${s.device_platform}${s.device_app_version ? ` ${s.device_app_version}` : ''}`
        );
      }
      if (s.out_of_geofence) meta.push(labels.outOfArea);
      if (s.suspicious_mock_location) meta.push(labels.mock);
      doc.fillColor('#475569').text(meta.join('    '), { width: contentW });
      if (s.notes) doc.text(`${labels.notes}: ${s.notes}`, { width: contentW });
      if (deleted) {
        doc
          .fillColor('#b91c1c')
          .text(
            `${labels.deletedBy}: ${s.deleted_by_name ?? '—'}, ${fmtDateTime(s.deleted_at, lang, timeZone)}` +
              (s.deletion_reason ? ` — ${labels.reason}: ${s.deletion_reason}` : ''),
            { width: contentW }
          );
      }

      if (s.history.length > 0) {
        ensureSpace(30);
        doc.moveDown(0.15);
        doc.font('Helvetica-Bold').fontSize(8).fillColor('#64748b').text(labels.trail);
        doc.font('Helvetica').fontSize(8).fillColor('#475569');
        for (const ev of s.history) renderTrailEvent(ev);
      }

      doc.moveDown(0.5);
    }

    function renderTrailEvent(ev: StampHistoryEvent): void {
      ensureSpace(18);
      const when = fmtDateTime(ev.recorded_at, lang, timeZone);
      const who = ev.actor_name ?? '—';
      const head = `• ${when} — ${KIND_LABEL[lang][ev.kind]} — ${who}`;
      doc.text(head, { width: contentW, indent: 6 });
      if (ev.justification) {
        doc.text(`${labels.reason}: ${ev.justification}`, { width: contentW, indent: 18 });
      }
      for (const ch of ev.changes) {
        const before = fmtFieldValue(ch.field, ch.before, lang, timeZone, labels);
        const after = fmtFieldValue(ch.field, ch.after, lang, timeZone, labels);
        // '»' and not '→': pdfkit's built-in Helvetica is WinAnsi-encoded and
        // has no U+2192, which prints as garbage instead of an arrow.
        doc.text(`${FIELD_LABEL[lang][ch.field]}: ${before}  »  ${after}`, {
          width: contentW,
          indent: 18,
        });
      }
    }

    doc.end();
  });
}
