#!/usr/bin/env bash
#
# publish-ota.sh — ship a JS/TS-only update to the sonoQui mobile app without a
# store review, by publishing a new bundle to the self-hosted OTA server
# (expo-open-ota at https://ota.sonoqui.pro).
#
# Run from your dev machine (this is the local equivalent of Penno's
# mobile-ota GitHub Action — sonoQui deploys manually, so OTA does too).
#
#   apps/mobile/scripts/publish-ota.sh              # → staging  (TestFlight / internal)
#   apps/mobile/scripts/publish-ota.sh --production # → production (App Store / Play prod)
#   apps/mobile/scripts/publish-ota.sh --branch foo # → arbitrary branch
#   apps/mobile/scripts/publish-ota.sh --seed       # re-baseline the fingerprint gate
#   apps/mobile/scripts/publish-ota.sh --force      # publish even if the gate trips
#
# Prerequisites (one-time):
#   - credentials/private-key.pem present locally (gitignored; generated by
#     `npx expo-updates codesigning:generate`, also copied to the server).
#   - Logged into Expo (`npx eas login`) OR EXPO_TOKEN exported. The OTA server
#     resolves channel → branch against Expo's API, so the publisher must auth
#     as the project owner (micheel93-2).
#
# The fingerprint gate: runtimeVersion is a STATIC string (app.json >
# runtimeVersion). A JS-only change keeps the project's @expo/fingerprint hash
# stable; a native change (dep bump, plugin, ios/android, app config touching
# native) flips it. This script refuses to publish when the live hash differs
# from .native-fingerprint.json — that divergence means the bundle would be
# incompatible with the shipped binary. Rebuild natively, bump runtimeVersion,
# re-seed (--seed), then ship a new binary instead.
set -euo pipefail

# Pin tool versions so the hash this script computes matches the one the native
# build embeds (drift between @expo/fingerprint versions = false gate trips).
EOAS_VERSION="2.3.19"
FINGERPRINT_VERSION="0.19.3"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
BASELINE_FILE="${MOBILE_DIR}/.native-fingerprint.json"
PRIVATE_KEY="${MOBILE_DIR}/credentials/private-key.pem"

BRANCH="staging"
FORCE=0
SEED=0

while [ $# -gt 0 ]; do
  case "$1" in
    --production|--prod) BRANCH="production" ;;
    --staging)           BRANCH="staging" ;;
    --branch)            shift; BRANCH="${1:?--branch needs a value}" ;;
    --force)             FORCE=1 ;;
    --seed)              SEED=1 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//' | head -40
      exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

cd "${MOBILE_DIR}"

echo "==> Computing @expo/fingerprint hash…"
CURRENT_HASH="$(npx -y "@expo/fingerprint@${FINGERPRINT_VERSION}" fingerprint:generate . \
  | node -e 'let i="";process.stdin.on("data",d=>i+=d).on("end",()=>console.log(JSON.parse(i).hash))')"
RUNTIME_VERSION="$(node -e "console.log(require('./app.json').expo.runtimeVersion)")"
echo "    current fingerprint : ${CURRENT_HASH}"
echo "    runtimeVersion      : ${RUNTIME_VERSION}"

if [ "${SEED}" = "1" ]; then
  node -e "require('fs').writeFileSync('${BASELINE_FILE}', JSON.stringify({ hash: '${CURRENT_HASH}', runtimeVersion: '${RUNTIME_VERSION}', updatedAt: new Date().toISOString() }, null, 2) + '\n')"
  echo "==> Re-seeded ${BASELINE_FILE} (hash=${CURRENT_HASH}, runtimeVersion=${RUNTIME_VERSION})."
  echo "    Commit it: git add apps/mobile/.native-fingerprint.json"
  exit 0
fi

if [ ! -f "${BASELINE_FILE}" ]; then
  echo "!!  No ${BASELINE_FILE}. Seed it after your first OTA-enabled native build:" >&2
  echo "      $0 --seed" >&2
  [ "${FORCE}" = "1" ] || exit 1
fi

BASELINE_HASH="$(node -e "try{console.log(require('${BASELINE_FILE}').hash)}catch{console.log('')}")"
if [ -n "${BASELINE_HASH}" ] && [ "${CURRENT_HASH}" != "${BASELINE_HASH}" ]; then
  echo "" >&2
  echo "❌ Native fingerprint changed since the last native build." >&2
  echo "     baseline : ${BASELINE_HASH}" >&2
  echo "     current  : ${CURRENT_HASH}" >&2
  echo "" >&2
  echo "   A native-level change (dep/plugin/ios/android/app config) is NOT" >&2
  echo "   OTA-safe — the bundle would mismatch the shipped binary. Instead:" >&2
  echo "     1. Bump app.json > runtimeVersion (e.g. \"1\" → \"2\")." >&2
  echo "     2. npm run prebuild && rebuild in Xcode / Android Studio, submit." >&2
  echo "     3. Once the new binary is live, re-seed: $0 --seed" >&2
  echo "" >&2
  echo "   To OTA anyway (you are SURE the change is JS-only): --force" >&2
  [ "${FORCE}" = "1" ] || exit 1
  echo "   (--force given; publishing despite the mismatch.)" >&2
fi

if [ ! -f "${PRIVATE_KEY}" ]; then
  echo "❌ Missing ${PRIVATE_KEY}. Bundles must be code-signed." >&2
  echo "   Copy the OTA private key here (it is gitignored), or regenerate the" >&2
  echo "   keypair with: npx expo-updates codesigning:generate …" >&2
  exit 1
fi

# Stamp the bundle with its source commit. EXPO_PUBLIC_* vars are inlined by
# Metro into the shipped JS so it can be identified at runtime.
export EXPO_PUBLIC_COMMIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

echo "==> Publishing to branch '${BRANCH}' (commit ${EXPO_PUBLIC_COMMIT_SHA})…"
npx -y "eoas@${EOAS_VERSION}" publish \
  --platform all \
  --branch "${BRANCH}" \
  --nonInteractive \
  --disableRepositoryCheck

echo ""
echo "✅ Published to '${BRANCH}'."
echo "   Devices on a binary with channel '${BRANCH}' pick it up on next cold launch"
echo "   (or sooner via the in-app useUpdateGate foreground check)."
echo "   Server: https://ota.sonoqui.pro/dashboard"
