#!/usr/bin/env node
/**
 * Build-time CSP hash generator.
 *
 * Astro inlines the small per-component module scripts straight into each page
 * (mobile menu, Turnstile loader, contact form, carousels…), so a
 * `script-src` that does not say `'unsafe-inline'` has to list their hashes.
 * They change whenever that component's code changes, so the list is generated
 * here rather than written by hand in `nginx.conf`.
 *
 * Output is an nginx snippet defining one variable, included from the server
 * block and interpolated into the Content-Security-Policy-Report-Only header:
 *
 *     set $csp_script_hashes "'sha256-…' 'sha256-…'";
 *
 * `<script type="application/ld+json">` blocks are deliberately skipped: they
 * are data blocks, never executed, and browsers do not apply `script-src` to
 * them (verified in Chromium — an inline classic script is reported, the
 * JSON-LD next to it is not). Hashing them would add ~47 hashes per build for
 * nothing.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const distDir = join(root, "dist");
const outFile = join(root, "csp", "script-hashes.conf");

const htmlFiles = [];
(function walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (entry.name.endsWith(".html")) htmlFiles.push(full);
  }
})(distDir);

const SCRIPT = /<script([^>]*)>([\s\S]*?)<\/script>/gi;
const hashes = new Set();

for (const file of htmlFiles) {
  const html = readFileSync(file, "utf8");
  for (const [, attrs, body] of html.matchAll(SCRIPT)) {
    if (/\ssrc=/i.test(attrs)) continue; // external file: covered by 'self'
    const type = attrs.match(/type=["']([^"']+)["']/i)?.[1] ?? "";
    if (type.includes("json")) continue; // data block, not executed
    if (!body.trim()) continue;
    hashes.add(createHash("sha256").update(body, "utf8").digest("base64"));
  }
}

const sorted = [...hashes].sort();
const value = sorted.map((h) => `'sha256-${h}'`).join(" ");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  [
    "# Generated by scripts/csp-hashes.mjs during `npm run build` — do not edit.",
    `# ${sorted.length} inline script(s) across ${htmlFiles.length} page(s).`,
    `set $csp_script_hashes "${value}";`,
    "",
  ].join("\n"),
);

console.log(`[csp] ${sorted.length} inline script hash(es) from ${htmlFiles.length} page(s) -> csp/script-hashes.conf`);
